<div class="container">
    <div class="login">
        <form class="login-container needs-validation" novalidate>
            <label class="form-label" for="email"><?= $i_login_email ?></label>
            <input class="form-control" type="text" name="email" id="email" required>
            <p class="login-form-error d-none" id="emailError"><?= $i_login_email_mandatory ?></p>
            <p class="login-form-error d-none" id="emailFormatError"><?= $i_login_email_format ?></p>
            <label class="form-label mt-3" for="password"><?= $i_login_password ?></label>
            <input class="form-control" type="password" name="password" id="password" required>
            <p class="login-form-error d-none" id="passwordError"><?= $i_login_password_mandatory ?></p>
            <button type="button" id="loginButton" class="btn btn-primary mt-3 align-self-end bg-secondary-color text-primary-color"><?= $i_login_button ?></button>
            <p class="mt-3"><?= $i_login_register_text ?> <a href="register"><?= $i_login_register ?></a></p>
        </form>
    </div>
</div>
<script type="module" src="pages/login/login.scripts.js"></script>