<div class="container">
    <div class="register">
        <form class="register-container needs-validation" novalidate>
            <label class="form-label" for="name"><?= $i_register_name ?></label>
            <input class="form-control" type="text" name="name" id="name" required>
            <p class="register-form-error d-none" id="nameError"><?= $i_register_name_mandatory ?></p>
            <label class="form-label" for="surname"><?= $i_register_surname ?></label>
            <input class="form-control" type="text" name="surname" id="surname" required>
            <p class="register-form-error d-none" id="surnameError"><?= $i_register_surname_mandatory ?></p>
            <label class="form-label" for="email"><?= $i_register_email ?></label>
            <input class="form-control" type="text" name="email" id="email" required>
            <p class="register-form-error d-none" id="emailError"><?= $i_register_email_mandatory ?></p>
            <p class="register-form-error d-none" id="emailFormatError"><?= $i_register_email_format ?></p>
            <label class="form-label" for="birthDate"><?= $i_register_birth_date ?></label>
            <input class="form-control" type="date" name="birthDate" id="birthDate" required>
            <p class="register-form-error d-none" id="birthDateError"><?= $i_register_birth_date_mandatory ?></p>
            <label class="form-label" for="password"><?= $i_register_password ?></label>
            <input class="form-control" type="password" name="password" id="password" required>
            <p class="register-form-error d-none" id="passwordError"><?= $i_register_password_mandatory ?></p>
            <label class="form-label" for="confirmPassword"><?= $i_register_confirm_password ?></label>
            <input class="form-control" type="password" name="confirmPassword" id="confirmPassword" required>
            <p class="register-form-error d-none" id="confirmPasswordError"><?= $i_register_confirm_password_mandatory ?></p>
            <p class="register-form-error d-none" id="passwordMismatchError"><?= $i_register_confirm_password_missmatch ?></p>
            <button type="button" class="btn btn-primary mt-3 align-self-end bg-secondary-color text-primary-color" id="registerButton"><?= $i_register_button ?></button>
        </form>
    </div>
</div>
<script type="module" src="pages/register/register.scripts.js"></script>