<div class="container pb-5">
    <div class="product mt-5">
        <div class="row mb-5">
            <div class="col-3">
                <!-- PHOTO -->
            </div>
            <div class="col-9">
                <h3 class="product-title"><?= $product['name'] ?></h3>
                <p class="product-subtitle"><?= $product['company'] ?> - <?= $product['type'] ?></p>
                <div class="product-price">
                    <?php if ($product['offer']) : ?>
                        <p class="product-current-price"><?= $product['offer'] ?>€</p>
                    <p class="product-previous-price"><?= $product['price'] ?>€</p>
                    <?php else : ?>
                    <p class="product-current-price"><?= $product['price'] ?>€</p>
                    <?php endif; ?>
                </div>
                <p class="product-description"><?= $product['description'] ?></p>
                <div>
                    <span class="fa-star <?php if ($product['rating'] > 0) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                    <span class="fa-star <?php if ($product['rating'] >= 1) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                    <span class="fa-star <?php if ($product['rating'] >= 2) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                    <span class="fa-star <?php if ($product['rating'] >= 3) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                    <span class="fa-star <?php if ($product['rating'] >= 4) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                </div>
                <div class="d-flex align-items-center mt-3">
                    <label for="quantity" class="me-3">Quantity</label>
                    <input type="number" name="quantity" id="quantity" class="form-control" value="1">
                </div>
                <input type="hidden" name="productId" id="productId" value="<?= $product['id'] ?>">
                <button class="btn btn-primary mt-3 mb-3" type="button" id="addToCart">Add to shopping cart</button>
            </div>
        </div>
        <hr>
        <h4 class="mt-5 mb-3">Products of same type</h4>
        <div class="row mb-4">
            <?php foreach ($sameTypeProducts as $sameTypeProduct) : ?>
                <div class="col-3 mb-3 product-card" data-company="<?= $sameTypeProduct['company'] ?>" data-type="<?= $sameTypeProduct['type'] ?>">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"><?= $sameTypeProduct['name'] ?></h5>
                            <h6 class="card-subtitle mb-2 text-muted"><?= $sameTypeProduct['company'] ?></h6>
                            <p class="card-text"><?= $sameTypeProduct['description'] ?></p>
                            <div class="product-price">
                                <?php if ($sameTypeProduct['offer']) : ?>
                                    <p class="product-current-price"><?= $sameTypeProduct['offer'] ?>€</p>
                                <p class="product-previous-price"><?= $sameTypeProduct['price'] ?>€</p>
                                <?php else : ?>
                                <p class="product-current-price"><?= $sameTypeProduct['price'] ?>€</p>
                                <?php endif; ?>
                            </div>
                            <div>
                                <span class="fa-star <?php if ($sameTypeProduct['rating'] > 0) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                                <span class="fa-star <?php if ($sameTypeProduct['rating'] >= 1) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                                <span class="fa-star <?php if ($sameTypeProduct['rating'] >= 2) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                                <span class="fa-star <?php if ($sameTypeProduct['rating'] >= 3) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                                <span class="fa-star <?php if ($sameTypeProduct['rating'] >= 4) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                            </div>
                            <a href="<?= $sameTypeProduct['link'] ?>" class="card-link">Ver producto</a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
        <h4 class="mb-3">Products of same company</h4>
        <div class="row mb-5">
            <?php foreach ($sameCompanyProducts as $sameCompanyProduct) : ?>
                <div class="col-3 mb-3 product-card" data-company="<?= $sameCompanyProduct['company'] ?>" data-type="<?= $sameCompanyProduct['type'] ?>">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title"><?= $sameCompanyProduct['name'] ?></h5>
                            <h6 class="card-subtitle mb-2 text-muted"><?= $sameCompanyProduct['company'] ?></h6>
                            <p class="card-text"><?= $sameCompanyProduct['description'] ?></p>
                            <div class="product-price">
                                <?php if ($sameCompanyProduct['offer']) : ?>
                                    <p class="product-current-price"><?= $sameCompanyProduct['offer'] ?>€</p>
                                <p class="product-previous-price"><?= $sameCompanyProduct['price'] ?>€</p>
                                <?php else : ?>
                                <p class="product-current-price"><?= $sameCompanyProduct['price'] ?>€</p>
                                <?php endif; ?>
                            </div>
                            <div>
                                <span class="fa-star <?php if ($sameCompanyProduct['rating'] > 0) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                                <span class="fa-star <?php if ($sameCompanyProduct['rating'] >= 1) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                                <span class="fa-star <?php if ($sameCompanyProduct['rating'] >= 2) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                                <span class="fa-star <?php if ($sameCompanyProduct['rating'] >= 3) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                                <span class="fa-star <?php if ($sameCompanyProduct['rating'] >= 4) { echo 'fa checked'; } else { echo 'far'; } ?>"></span>
                            </div>
                            <a href="<?= $sameCompanyProduct['link'] ?>" class="card-link">Ver producto</a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>
<script type="module" src="pages/product/product.scripts.js"></script>