<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" id="dynamicStylesheet" href="pages/home/home.styles.css">
    <title>Document</title>
</head>
<body>
    <div class="header">
        <p>Header works!</p>
    </div>
    <script type="module" src="pages/scripts.js"></script>
    <script type="module" src="pages/shared/header/header.scripts.js"></script>