<div class="container mt-5">
    <div class="row">
        <?php if (!isset($purchase) || empty($purchase)) : ?>
            <div class="col-12">
                <p>El recibo al que estás intentando acceder no existe o no se corresponde a tu usuario.</p>
            </div>
        <?php else : ?>
            <div class="col-12">
            <?php foreach ($purchase['products'] as $product) : ?>
                <div class="shopping-cart-product-list mb-4" id="shoppingCartItem<?= $product['id'] ?>">
                    <div class="row">
                        <div class="col-3">
                            <!-- PHOTO -->
                        </div>
                        <div class="col-9 d-flex justify-content-between ps-4 pe-5 py-3 align-items-end">
                            <div>
                                <p class="product-title"><?= $product['name'] ?></p>
                                <!-- <p><?= $product['company'] ?></p> -->
                                <div class="d-flex">
                                    <?php if ($product['offer']) : ?>
                                    <p class="product-current-price"><?= $product['offer'] ?>€</p>
                                    <p class="product-previous-price"><?= $product['price'] ?>€</p>
                                    <?php else : ?>
                                    <p class="product-current-price"><?= $product['price'] ?>€</p>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <span class="m-0 me-3">Quantity: x<?= $product['quantity'] ?></span>
                                </div>
                                <?php if ($product['offer']) : ?>
                                    <p class="product-total-price" data-price="<?= $product['offer'] ?>">Total: <?= $product['offer'] * $product['quantity'] ?>€</p>
                                    <?php else : ?>
                                    <p class="product-total-price" data-price="<?= $product['offer'] ?>">Total: <?= $product['price'] * $product['quantity'] ?>€</p>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
                <div class="row mt-5">
                    <div class="col-6">
                        <p>Fecha tramitación pedido: <?= $purchase['finished_at'] ?></p>
                        <h1>Total: <?= $total ?>€</h1>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
<script type="module" src="pages/receipt/receipt.scripts.js"></script>