<div class="container mt-5">
    <div class="shopping-cart" id="shoppingCartContainer">
        <?php if (!isset($shoppingCart) || empty($shoppingCart)) : ?>
            <p>Bienvenido a la tienda virtual de la UOC.</p>
            <p>Actualmente no tiene ningún producto en el carrito, por favor visite <a href="home">nuestra tienda</a> o <a href="login">inicie sesión</a> para acceder al carrito de su usuario.</p>
        <?php else : ?>
            <?php if (strpos($_COOKIE['userId'], 'e_')) : ?>
            <p>¡Bienvenido invitado!</p> 
            <p>Para gozar de todas las ventajas que ofrecemos a nuestros usuarios, no dudes en <a href="register">registrarte</a>, o <a href="login">iniciar sesión</a> si ya eres usuario.</p>
            <?php else : ?>
            <p>¡Bienvenido "usuario"!</p>
            <?php endif; ?>
            <?php foreach($shoppingCart['products'] as $product) : ?>
            <div class="shopping-cart-product-list mb-4" id="shoppingCartItem<?= $product['id'] ?>">
                <div class="row">
                    <div class="col-3">
                        <!-- PHOTO -->
                    </div>
                    <div class="col-9 d-flex justify-content-between px-4 py-3 align-items-end">
                        <div>
                            <p class="product-title"><?= $product['name'] ?></p>
                            <!-- <p><?= $product['company'] ?></p> -->
                            <div class="d-flex">
                                <?php if ($product['offer']) : ?>
                                <p class="product-current-price"><?= $product['offer'] ?>€</p>
                                <p class="product-previous-price"><?= $product['price'] ?>€</p>
                                <?php else : ?>
                                <p class="product-current-price"><?= $product['price'] ?>€</p>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div>
                            <div class="d-flex justify-content-between align-items-center">
                                <span class="m-0 me-3">Quantity: </span>
                                <select class="form-control" name="productQuantity" id="productQuantity<?= $product['id'] ?>">
                                    <option value="1" <?php if ($product['quantity'] === 1) { echo 'selected'; } ?>>1</option>
                                    <option value="2" <?php if ($product['quantity'] === 2) { echo 'selected'; } ?>>2</option>
                                    <option value="3" <?php if ($product['quantity'] === 3) { echo 'selected'; } ?>>3</option>
                                    <option value="4" <?php if ($product['quantity'] === 4) { echo 'selected'; } ?>>4</option>
                                    <option value="5" <?php if ($product['quantity'] === 5) { echo 'selected'; } ?>>5</option>
                                    <option value="6" <?php if ($product['quantity'] === 6) { echo 'selected'; } ?>>6</option>
                                    <option value="7" <?php if ($product['quantity'] === 7) { echo 'selected'; } ?>>7</option>
                                    <option value="8" <?php if ($product['quantity'] === 8) { echo 'selected'; } ?>>8</option>
                                    <option value="9" <?php if ($product['quantity'] === 9) { echo 'selected'; } ?>>9</option>
                                    <option value="10" <?php if ($product['quantity'] === 10) { echo 'selected'; } ?>>10</option>
                                </select>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash remove-product" viewBox="0 0 16 16" id="removeProduct<?= $product['id'] ?>">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </div>
                            <?php if ($product['offer']) : ?>
                                <p class="product-total-price" data-price="<?= $product['offer'] ?>">Total: <?= $product['offer'] * $product['quantity'] ?>€</p>
                                <?php else : ?>
                                <p class="product-total-price" data-price="<?= $product['offer'] ?>">Total: <?= $product['price'] * $product['quantity'] ?>€</p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach; ?>
            <a href="purchase-details" class="btn btn-primary shopping-cart-purchase bg-primary-color text-secondary-color">Tramitar pedido</a>
        <?php endif; ?>
    </div>
</div>
<script type="module" src="pages/shopping-cart/shopping-cart.scripts.js"></script>