<div class="container mt-5">
    <?php if (isset($shoppingCart) && !empty($shoppingCart) && count($shoppingCart['products']) > 0) : ?>
        <h4>Resumen del pedido</h4>
        <?php foreach ($shoppingCart['products'] as $product) : ?>
            <div class="shopping-cart-product-list mb-4" id="shoppingCartItem<?= $product['id'] ?>">
                <div class="row">
                    <div class="col-3">
                        <!-- PHOTO -->
                    </div>
                    <div class="col-9 d-flex justify-content-between ps-4 pe-5 py-3 align-items-end">
                        <div>
                            <p class="product-title"><?= $product['name'] ?></p>
                            <!-- <p><?= $product['company'] ?></p> -->
                            <div class="d-flex">
                                <?php if ($product['offer']) : ?>
                                <p class="product-current-price"><?= $product['offer'] ?>€</p>
                                <p class="product-previous-price"><?= $product['price'] ?>€</p>
                                <?php else : ?>
                                <p class="product-current-price"><?= $product['price'] ?>€</p>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div>
                            <div class="d-flex justify-content-between align-items-center">
                                <span class="m-0 me-3">Quantity: x<?= $product['quantity'] ?></span>
                            </div>
                            <?php if ($product['offer']) : ?>
                                <p class="product-total-price" data-price="<?= $product['offer'] ?>">Total: <?= $product['offer'] * $product['quantity'] ?>€</p>
                                <?php else : ?>
                                <p class="product-total-price" data-price="<?= $product['offer'] ?>">Total: <?= $product['price'] * $product['quantity'] ?>€</p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
        <div class="row">
            <div class="col-6">
                <h4>Método de pago</h4>
                <?php if (isset($paymentMethods) && !empty($paymentMethods)) : ?>
                    <div id="paymentMethodContainer">
                        <?php foreach ($paymentMethods as $paymentMethod) : ?>
                            <?php if ($paymentMethod['payment_type'] == 1): ?>
                                <input type="radio" name="paymentMethod" id="paymentMethod<?= $paymentMethod['id'] ?>" value="<?= $paymentMethod['id'] ?>"/>
                                <label for="paymentMethod<?= $paymentMethod['id'] ?>" class="payment-method-label">Paypal: <?= $paymentMethod['paypal_user'] ?></label>
                            <?php else : ?>
                                <input type="radio" name="paymentMethod" id="paymentMethod<?= $paymentMethod['id'] ?>" value="<?= $paymentMethod['id'] ?>"/>
                                <label for="paymentMethod<?= $paymentMethod['id'] ?>" class="payment-method-label">Credit card: <?= $paymentMethod['credit_card'] ?></label>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <div class="accordion mt-3" id="accordionPaymentMethod">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingPaymentMethod">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapsePaymentMethod" aria-expanded="false" aria-controls="collapsePaymentMethod">
                                Añadir método de pago
                            </button>
                        </h2>
                        <div id="collapsePaymentMethod" class="accordion-collapse collapse" aria-labelledby="headingPaymentMethod" data-bs-parent="#accordionPaymentMethod">
                            <div class="accordion-body">
                                <label class="form-label" for="paymentMethodType">Tipo</label>
                                <select class="form-control" name="paymentMethodType" id="paymentMethodType">
                                    <option value="1">Paypal</option>
                                    <option value="2">Credit Card</option>
                                </select>
                                <label class="form-label" for="paymentMethodValue">Paypal user/credit card number</label>
                                <input class="form-control" type="text" name="paymentMethodValue" id="paymentMethodValue">
                                <button class="btn btn-primary shopping-cart-purchase bg-primary-color text-secondary-color mt-3" id="savePaymentMethod">Guardar método de pago</button>
                            </div>
                        </div>
                    </div>
                </div>                
            </div>
            <div class="col-6">
                <h4>Dirección de envio</h4>
                <?php if (isset($sendingDestinations) && !empty($sendingDestinations)) : ?>
                    <div id="sendingContainer">
                        <?php foreach ($sendingDestinations as $sendingDestination) : ?>
                            <input type="radio" name="sendingDestination" id="sendingDestination<?= $sendingDestination['id'] ?>" value="<?= $sendingDestination['id'] ?>"/>                        
                            <label for="sendingDestination<?= $sendingDestination['id'] ?>" class="direction-label">Street: <?= $sendingDestination['street'] ?></label>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <div class="accordion mt-3" id="accordionDirection">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="headingDirection">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseDirection" aria-expanded="false" aria-controls="collapseDirection">
                                Añadir dirección de envio
                            </button>
                        </h2>
                        <div id="collapseDirection" class="accordion-collapse collapse" aria-labelledby="headingDirection" data-bs-parent="#accordionDirection">
                            <div class="accordion-body">
                                <label class="form-label" for="directionName">Name</label>
                                <input class="form-control" type="text" name="directionName" id="directionName">
                                <label class="form-label" for="directionSurname">Surname</label>
                                <input class="form-control" type="text" name="directionSurname" id="directionSurname">
                                <label class="form-label" for="directionStreet">Street</label>
                                <input class="form-control" type="text" name="directionStreet" id="directionStreet">
                                <label class="form-label" for="directionPostalCode">Postal Code</label>
                                <input class="form-control" type="text" name="directionPostalCode" id="directionPostalCode">
                                <label class="form-label" for="directionCountry">Country</label>
                                <input class="form-control" type="text" name="directionCountry" id="directionCountry">
                                <label class="form-label" for="directionPhone">Phone</label>
                                <input class="form-control" type="text" name="directionPhone" id="directionPhone">
                                <label class="form-label" for="directionEmail">Email</label>
                                <input class="form-control" type="text" name="directionEmail" id="directionEmail">
                                <button class="btn btn-primary shopping-cart-purchase bg-primary-color text-secondary-color mt-3" id="saveDirection">Guardar dirección de envio</button>
                            </div>
                        </div>
                    </div>
                </div>                
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-6">
                <h1>Total: <?= $total ?>€</h1>
            </div>
            <div class="col-6">
                <button class="btn btn-primary shopping-cart-purchase bg-primary-color text-secondary-color" id="processPurchase">Tramitar pedido</button>
            </div>
        </div>
    <?php else : ?>
        <p>Actualmente no tiene ningún producto en el carrito, por favor visite <a href="home">nuestra tienda</a> o <a href="login">inicie sesión</a> para acceder al carrito de su usuario.</p>
    <?php endif; ?>
    
</div>
<script type="module" src="pages/purchase-details/purchase-details.scripts.js"></script>