    </div>
    <div class="footer bg-primary-color">
        <p class="text-secondary-color">Comercio Electrónico | Práctica 1 | imolinava</p>
    </div>
    <script type="module" src="pages/shared/footer/footer.scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>